stages:
  - build
  - test

workflow:
  rules:
    - when: always

install-deps:
  image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
  stage: build
  script:
    - npm ci

ui-chrome-tests:
  image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
  stage: test
  script:
    - npm ci
    - npm start &
    - npx cypress run --browser chrome
